### PR TITLE
Frontend init

### PR DESCRIPTION
**Pull request by komeally**
Team 1 was thinking of using React as a possible frontend since most of us were familiar with the library (merging with dev)

### CODE REVIEW

**Comment by dogwaterdev1** [comment]
Overall I like adding a frontend. Let's clear it with at least half of the rest of the team to get full approval

**Review by dogwaterdev1 — COMMENTED** [review]
I personally like these changes and don't see anything breaking with the backend. Just want to make sure we have a democratic vote to add it quick

**Review by shokoladber — APPROVED** [review]
Seems good to me

**Comment by Astro713** [comment]
Good to me as well !

**Review by Astro713 — APPROVED** [review]

**Review by Astro713 — APPROVED** [review]

**Review by shokoladber — APPROVED** [review]

**Review by luvkogepan — APPROVED** [review]
lgtm

**Review by dogwaterdev1 — APPROVED** [review]
Approving changes. Frontend separation might be subject to change in the future. TBD

**Pull request merged**
